name: Contributors

on:
  push:
    branches:
    - contributors
    paths:
    - dev-aliases.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      with:
        cancel_others: 'true'
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install PyGithub PyYAML
    - name: Run script
      run: python scripts/update_contributors.py
      env:
        GITHUB_PAT_AUTH: ${{secrets.GITHUB_TOKEN}}
    - name: Test diff
      id: check
      run: echo "modified=$(git diff --quiet HEAD -- docs/contributors.md && echo false || echo true)" >> "$GITHUB_OUTPUT"
    - name: Push changes
      if: steps.check.outputs.modified == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email ''
        git commit -am "Update contributors"
        git push
